version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t vacationrentalpricingestimator .
  build:
    commands:
      - docker images
      - docker run vacationrentalpricingestimator echo "Success!" 