"""empty message

Revision ID: 5686f2f52243
Revises: a37de4c75906
Create Date: 2021-12-08 09:33:12.810218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5686f2f52243'
down_revision = 'a37de4c75906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('HostResponseTime', sa.Integer(), nullable=False),
    sa.Column('RoomType', sa.Integer(), nullable=False),
    sa.Column('Beds', sa.Integer(), nullable=False),
    sa.Column('Accommodates', sa.Integer(), nullable=False),
    sa.Column('Longitude', sa.Float(), nullable=False),
    sa.Column('Latitude', sa.Float(), nullable=False),
    sa.Column('ReviewScore', sa.Float(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
