"""empty message

Revision ID: 7c762df5672c
Revises: 5686f2f52243
Create Date: 2021-12-08 12:10:05.884448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c762df5672c'
down_revision = '5686f2f52243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('HostResponseTime', sa.Integer(), nullable=False),
    sa.Column('RoomType', sa.Integer(), nullable=False),
    sa.Column('Beds', sa.Integer(), nullable=False),
    sa.Column('Accommodates', sa.Integer(), nullable=False),
    sa.Column('Longitude', sa.Float(), nullable=False),
    sa.Column('Latitude', sa.Float(), nullable=False),
    sa.Column('ReviewScore', sa.Float(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    op.drop_table('users')
    # ### end Alembic commands ###
