"""empty message

Revision ID: e36c9dc16734
Revises: 
Create Date: 2022-07-01 14:38:08.571644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36c9dc16734'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings_postgres_clone3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_response_rate', sa.Integer(), nullable=True),
    sa.Column('host_is_superhost', sa.String(length=1), nullable=True),
    sa.Column('neighbourhood_cleansed', sa.String(length=512), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('property_type', sa.String(length=128), nullable=True),
    sa.Column('room_type', sa.String(length=128), nullable=True),
    sa.Column('accommodates', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('host_number_of_years', sa.Float(), nullable=True),
    sa.Column('host_response_time_a_few_days_or_more', sa.Integer(), nullable=True),
    sa.Column('host_response_time_within_a_day', sa.Integer(), nullable=True),
    sa.Column('host_response_time_within_a_few_hours', sa.Integer(), nullable=True),
    sa.Column('host_response_time_within_an_hour', sa.Integer(), nullable=True),
    sa.Column('closeness_to_landmark', sa.Float(), nullable=True),
    sa.Column('closeness_to_subway', sa.Float(), nullable=True),
    sa.Column('review_scores_rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews_clone_fin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=128), nullable=True),
    sa.Column('comments', sa.String(length=2048), nullable=True),
    sa.Column('polarity', sa.Float(), nullable=True),
    sa.Column('subjectivity', sa.Float(), nullable=True),
    sa.Column('reviewer_gender', sa.String(length=64), nullable=True),
    sa.Column('nouns', sa.String(length=512), nullable=True),
    sa.Column('adjectives', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('HostResponseTime', sa.Integer(), nullable=False),
    sa.Column('RoomType', sa.Integer(), nullable=False),
    sa.Column('Beds', sa.Integer(), nullable=False),
    sa.Column('Accommodates', sa.Integer(), nullable=False),
    sa.Column('Longitude', sa.Float(), nullable=False),
    sa.Column('Latitude', sa.Float(), nullable=False),
    sa.Column('ReviewScore', sa.Float(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    op.drop_table('users')
    op.drop_table('reviews_clone_fin')
    op.drop_table('listings_postgres_clone3')
    # ### end Alembic commands ###
